version: 0.0
os: linux
files:
  - source: /
    destination: /srv/snakeoil/
permissions:
  - object: /srv/snakeoil/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 20
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
